# Generated by Django 4.1.2 on 2022-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
