# Generated by Django 4.1.2 on 2022-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_alter_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
